### Get All Notifications
GET localhost:8080/api/v1/notification
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJva2lsb3Zub2RpcjQ1NkBnbWFpbC5jb20iLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiOTBjMTAwMWQtYzc4NS00Y2IzLWE0MGQtOTQ5YmY1ZDc5OGFiIiwiaWF0IjoxNzYzNTQwMjc4LCJleHAiOjE3NjM2MjY2Nzh9.HWRYBVc_yj_7xg2DLh2HZSGwo6S0Wtohs23en4ljZJ8

### Get Notification By ID
GET localhost:8080/api/v1/notification/55fc45e3-afa2-4e5e-af24-3a6e98eec118
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJva2lsb3Zub2RpcjQ1NkBnbWFpbC5jb20iLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiOTBjMTAwMWQtYzc4NS00Y2IzLWE0MGQtOTQ5YmY1ZDc5OGFiIiwiaWF0IjoxNzYzNTQwMjc4LCJleHAiOjE3NjM2MjY2Nzh9.HWRYBVc_yj_7xg2DLh2HZSGwo6S0Wtohs23en4ljZJ8

### Delete Notification By ID
DELETE localhost:8080/api/v1/notification/8e9572a0-e175-4bf0-85b0-6047544794cd
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJva2lsb3Zub2RpcjQ1NkBnbWFpbC5jb20iLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiOTBjMTAwMWQtYzc4NS00Y2IzLWE0MGQtOTQ5YmY1ZDc5OGFiIiwiaWF0IjoxNzYyNTM0NTA1LCJleHAiOjE3NjI2MjA5MDV9.PkUpPBS1mn0wD8wUUunGggQ9XGEA6oC-9UBGvCS3qvo